# Generated by Django 4.2.7 on 2023-11-23 09:22

import django.core.validators
from django.db import migrations, models
import re
import social_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_alter_post_created_at_alter_user_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[social_app.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, validators=[social_app.models.validate_bad_words]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[social_app.models.valide_email, django.core.validators.EmailValidator(message='enter a valid email')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[social_app.models.validate_bad_words, django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
